from __future__ import annotations
from enum import Enum


class ValidationStatus(str, Enum):
    VALID = "VALID"
    VALID_HIGH_CONFIDENCE = "VALID_HIGH_CONFIDENCE"
    VALID_BUSINESS = "VALID_BUSINESS"
    VALID_FREE = "VALID_FREE"

    INVALID = "INVALID"
    INVALID_SYNTAX = "INVALID_SYNTAX"
    INVALID_DOMAIN = "INVALID_DOMAIN"
    INVALID_TLD = "INVALID_TLD"
    INVALID_MX = "INVALID_MX"
    INVALID_DISPOSABLE = "INVALID_DISPOSABLE"
    INVALID_ROLE = "INVALID_ROLE"
    INVALID_LENGTH = "INVALID_LENGTH"
    INVALID_LOCAL_PART = "INVALID_LOCAL_PART"
    INVALID_DOMAIN_PART = "INVALID_DOMAIN_PART"
    INVALID_UNICODE = "INVALID_UNICODE"
    INVALID_CONTROL_CHARACTER = "INVALID_CONTROL_CHARACTER"
    INVALID_RESERVED_DOMAIN = "INVALID_RESERVED_DOMAIN"
    INVALID_EXAMPLE_DOMAIN = "INVALID_EXAMPLE_DOMAIN"
    INVALID_PRIVATE_DOMAIN = "INVALID_PRIVATE_DOMAIN"
    INVALID_IP_LITERAL = "INVALID_IP_LITERAL"

    UNKNOWN = "UNKNOWN"
    SUSPICIOUS = "SUSPICIOUS"
    RISKY = "RISKY"


class DnsStatus(str, Enum):
    RESOLVED = "RESOLVED"
    NXDOMAIN = "NXDOMAIN"
    SERVFAIL = "SERVFAIL"
    TIMEOUT = "TIMEOUT"
    NO_MX_HAS_A = "NO_MX_HAS_A"
    NO_RECORDS = "NO_RECORDS"
    SKIPPED = "SKIPPED"
    ERROR = "ERROR"


class Recommendation(str, Enum):
    SAFE_TO_SEND = "SAFE_TO_SEND"
    LIKELY_SAFE = "LIKELY_SAFE"
    SEND_WITH_CAUTION = "SEND_WITH_CAUTION"
    HIGH_RISK = "HIGH_RISK"
    DO_NOT_SEND = "DO_NOT_SEND"
    INVALID = "INVALID"


class SendDecision(str, Enum):
    SEND = "SEND"
    REVIEW = "REVIEW"
    SKIP = "SKIP"


class CatchAllStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    POSSIBLE_CATCH_ALL = "POSSIBLE_CATCH_ALL"
    NOT_INDICATED = "NOT_INDICATED"


class MailboxStatus(str, Enum):
    MAILBOX_UNKNOWN = "MAILBOX_UNKNOWN"
